/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninandsignupRouteImport } from './routes/signinandsignup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVercelRouteImport } from './routes/api/vercel'
import { Route as ApiOpenrouterRouteImport } from './routes/api/openrouter'
import { Route as ApiMeshRouteImport } from './routes/api/mesh'
import { Route as OauthCallbackProviderRouteImport } from './routes/oauth/callback.$provider'

const SigninandsignupRoute = SigninandsignupRouteImport.update({
  id: '/signinandsignup',
  path: '/signinandsignup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVercelRoute = ApiVercelRouteImport.update({
  id: '/api/vercel',
  path: '/api/vercel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterRoute = ApiOpenrouterRouteImport.update({
  id: '/api/openrouter',
  path: '/api/openrouter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshRoute = ApiMeshRouteImport.update({
  id: '/api/mesh',
  path: '/api/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackProviderRoute = OauthCallbackProviderRouteImport.update({
  id: '/oauth/callback/$provider',
  path: '/oauth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signinandsignup': typeof SigninandsignupRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/openrouter': typeof ApiOpenrouterRoute
  '/api/vercel': typeof ApiVercelRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signinandsignup': typeof SigninandsignupRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/openrouter': typeof ApiOpenrouterRoute
  '/api/vercel': typeof ApiVercelRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signinandsignup': typeof SigninandsignupRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/openrouter': typeof ApiOpenrouterRoute
  '/api/vercel': typeof ApiVercelRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/signinandsignup'
    | '/api/mesh'
    | '/api/openrouter'
    | '/api/vercel'
    | '/oauth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/signinandsignup'
    | '/api/mesh'
    | '/api/openrouter'
    | '/api/vercel'
    | '/oauth/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/signinandsignup'
    | '/api/mesh'
    | '/api/openrouter'
    | '/api/vercel'
    | '/oauth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninandsignupRoute: typeof SigninandsignupRoute
  ApiMeshRoute: typeof ApiMeshRoute
  ApiOpenrouterRoute: typeof ApiOpenrouterRoute
  ApiVercelRoute: typeof ApiVercelRoute
  OauthCallbackProviderRoute: typeof OauthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signinandsignup': {
      id: '/signinandsignup'
      path: '/signinandsignup'
      fullPath: '/signinandsignup'
      preLoaderRoute: typeof SigninandsignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vercel': {
      id: '/api/vercel'
      path: '/api/vercel'
      fullPath: '/api/vercel'
      preLoaderRoute: typeof ApiVercelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter': {
      id: '/api/openrouter'
      path: '/api/openrouter'
      fullPath: '/api/openrouter'
      preLoaderRoute: typeof ApiOpenrouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh': {
      id: '/api/mesh'
      path: '/api/mesh'
      fullPath: '/api/mesh'
      preLoaderRoute: typeof ApiMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback/$provider': {
      id: '/oauth/callback/$provider'
      path: '/oauth/callback/$provider'
      fullPath: '/oauth/callback/$provider'
      preLoaderRoute: typeof OauthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninandsignupRoute: SigninandsignupRoute,
  ApiMeshRoute: ApiMeshRoute,
  ApiOpenrouterRoute: ApiOpenrouterRoute,
  ApiVercelRoute: ApiVercelRoute,
  OauthCallbackProviderRoute: OauthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
